# Generated by Django 2.2.3 on 2019-07-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190728_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'ProductImage', 'verbose_name_plural': 'ProductImages'},
        ),
    ]
